import { useCallback, useEffect, useState } from "react";
import { Check, ClipboardCopy, Download, RefreshCw, ShieldAlert } from "lucide-react";

import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Field, Input, Select, Textarea } from "@/components/ui/Field";
import { Modal } from "@/components/ui/Modal";
import { ErrorState, SkeletonText } from "@/components/ui/States";
import { useSettings } from "@/contexts/SettingsContext";
import { useToast } from "@/contexts/ToastContext";
import { ApiError, toApiError } from "@/services/api";
import { churnpilot } from "@/services/churnpilot";
import type { GeneratedMessageData, MessageChannel, MessageTone } from "@/types/api";
import { titleCase } from "@/utils/format";

export const CHANNEL_LABELS: Record<MessageChannel, string> = {
  email: "Email",
  whatsapp: "WhatsApp",
  sms: "SMS",
  sales_call: "Call script",
};

const TONES: MessageTone[] = ["professional", "friendly", "concise", "premium"];

export type ComposerTarget = {
  customerId: string;
  customerName: string;
  channel: MessageChannel;
};

/**
 * Draft editor for AI-generated outreach. Drafts are always editable and never sent:
 * the only exits are copy to clipboard or download as a text file.
 */
export function MessageComposer({
  target,
  onClose,
}: {
  target: ComposerTarget | null;
  onClose: () => void;
}) {
  const { notify } = useToast();
  const { preferences } = useSettings();
  const [tone, setTone] = useState<MessageTone>(preferences.defaultTone);
  const [message, setMessage] = useState<GeneratedMessageData | null>(null);
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<ApiError | null>(null);
  const [approved, setApproved] = useState(false);

  const generate = useCallback(
    async (selectedTone: MessageTone) => {
      if (!target) return;
      setLoading(true);
      setError(null);
      setApproved(false);
      try {
        const result = await churnpilot.generateMessage(target.customerId, {
          channel: target.channel,
          tone: selectedTone,
        });
        setMessage(result);
        setSubject(result.subject ?? "");
        setBody(result.body);
      } catch (cause) {
        setError(toApiError(cause));
      } finally {
        setLoading(false);
      }
    },
    [target],
  );

  useEffect(() => {
    if (!target) {
      setMessage(null);
      setSubject("");
      setBody("");
      setApproved(false);
      setError(null);
      return;
    }
    setTone(preferences.defaultTone);
    void generate(preferences.defaultTone);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [target?.customerId, target?.channel]);

  const copy = async () => {
    const text = subject ? `Subject: ${subject}\n\n${body}` : body;
    try {
      await navigator.clipboard.writeText(text);
      notify({ tone: "success", title: "Draft copied to clipboard" });
    } catch {
      notify({ tone: "error", title: "Clipboard unavailable", description: "Select the text manually to copy it." });
    }
  };

  const download = () => {
    const text = subject ? `Subject: ${subject}\n\n${body}` : body;
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${target?.channel ?? "message"}-draft.txt`;
    anchor.click();
    URL.revokeObjectURL(url);
    notify({ tone: "success", title: "Draft exported as a text file" });
  };

  const requiresApproval = preferences.requireApprovalBeforeExport;
  const exportBlocked = requiresApproval && !approved;

  return (
    <Modal
      open={Boolean(target)}
      onClose={onClose}
      title={target ? `${CHANNEL_LABELS[target.channel]} draft for ${target.customerName}` : "Draft"}
      description="Generated by Gemini from the customer's stored metrics. Review and edit before you use it — ChurnPilot never sends anything."
      footer={
        <div className="flex flex-wrap items-center justify-between gap-3">
          <span className="flex items-center gap-2 text-xs text-ink-700/75">
            <ShieldAlert aria-hidden="true" className="h-3.5 w-3.5" />
            Draft only. No message is delivered from this screen.
          </span>
          <div className="flex flex-wrap items-center gap-2">
            <Button
              variant={approved ? "secondary" : "primary"}
              size="sm"
              onClick={() => setApproved((current) => !current)}
              disabled={!message}
            >
              <Check aria-hidden="true" className="h-3.5 w-3.5" />
              {approved ? "Approved" : "Approve draft"}
            </Button>
            <Button variant="secondary" size="sm" onClick={() => void copy()} disabled={!message || exportBlocked}>
              <ClipboardCopy aria-hidden="true" className="h-3.5 w-3.5" />
              Copy
            </Button>
            <Button variant="secondary" size="sm" onClick={download} disabled={!message || exportBlocked}>
              <Download aria-hidden="true" className="h-3.5 w-3.5" />
              Export
            </Button>
          </div>
        </div>
      }
    >
      <div className="space-y-5">
        <div className="flex flex-wrap items-center gap-2">
          {target ? <Badge tone="info">{CHANNEL_LABELS[target.channel]}</Badge> : null}
          {message?.generated_by ? (
            <Badge tone={message.generated_by === "gemini" ? "ai" : "neutral"}>
              {message.generated_by === "gemini" ? "AI generated (Gemini)" : `Source: ${titleCase(message.generated_by)}`}
            </Badge>
          ) : null}
          <Badge tone="neutral">Status: {message ? titleCase(message.status) : "pending"}</Badge>
          <Badge tone="warning">Send status: not sent</Badge>
        </div>

        <div className="grid gap-4 sm:grid-cols-[1fr_auto] sm:items-end">
          <Field label="Tone" hint="Regenerating replaces the draft with a new Gemini response.">
            {({ id }) => (
              <Select
                id={id}
                value={tone}
                onChange={(event) => {
                  const next = event.target.value as MessageTone;
                  setTone(next);
                  void generate(next);
                }}
              >
                {TONES.map((option) => (
                  <option key={option} value={option}>
                    {titleCase(option)}
                  </option>
                ))}
              </Select>
            )}
          </Field>
          <Button variant="secondary" size="sm" loading={loading} onClick={() => void generate(tone)}>
            {!loading ? <RefreshCw aria-hidden="true" className="h-3.5 w-3.5" /> : null}
            Regenerate
          </Button>
        </div>

        {error ? (
          <ErrorState message={error.message} code={error.code} onRetry={() => void generate(tone)} />
        ) : loading && !message ? (
          <div className="space-y-3">
            <SkeletonText lines={2} />
            <SkeletonText lines={6} />
          </div>
        ) : message ? (
          <div className="space-y-4">
            {target?.channel === "email" ? (
              <Field label="Subject">
                {({ id }) => <Input id={id} value={subject} onChange={(event) => setSubject(event.target.value)} />}
              </Field>
            ) : null}
            <Field label="Message body" hint="Fully editable. Nothing here is filled in from outside the stored customer record.">
              {({ id }) => (
                <Textarea
                  id={id}
                  value={body}
                  onChange={(event) => setBody(event.target.value)}
                  className="min-h-[16rem] font-sans"
                />
              )}
            </Field>
            {exportBlocked ? (
              <p className="rounded-2xl bg-amber-50 px-4 py-3 text-xs leading-5 text-amber-900">
                Your workspace requires an explicit approval before copying or exporting a draft. Approve the draft when you
                are happy with the wording.
              </p>
            ) : null}
          </div>
        ) : null}
      </div>
    </Modal>
  );
}
