import { useState } from "react";
import { Sparkles } from "lucide-react";

import { CHANNEL_LABELS } from "@/components/retention/MessageComposer";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card, CardHeader, KeyValue } from "@/components/ui/Card";
import { ErrorState, SkeletonText } from "@/components/ui/States";
import { useToast } from "@/contexts/ToastContext";
import { toApiError } from "@/services/api";
import { churnpilot } from "@/services/churnpilot";
import type { MessageChannel, RetentionRecord } from "@/types/api";
import { formatDate, titleCase } from "@/utils/format";

const MESSAGE_CHANNELS: MessageChannel[] = ["email", "whatsapp", "sms", "sales_call"];

export function RetentionPanel({
  customerId,
  customerName,
  records,
  loading,
  error,
  onReload,
  onCompose,
}: {
  customerId: string;
  customerName: string;
  records: RetentionRecord[];
  loading: boolean;
  error: { message: string; code?: string | null } | null;
  onReload: () => void;
  onCompose: (channel: MessageChannel) => void;
}) {
  const { notify } = useToast();
  const [generating, setGenerating] = useState(false);
  const latest = records[0] ?? null;

  const generate = async () => {
    setGenerating(true);
    try {
      const record = await churnpilot.generateRetention(customerId);
      notify({
        tone: "success",
        title: "Retention recommendation created",
        description:
          record.source === "gemini"
            ? "Generated by Gemini and stored as a draft action."
            : "Gemini was unavailable, so the backend rule-based fallback was used.",
      });
      onReload();
    } catch (cause) {
      const failure = toApiError(cause);
      notify({ tone: "error", title: "Could not generate a recommendation", description: failure.message });
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Card>
      <CardHeader
        title="Retention recommendation"
        description="Strategy drafted in the backend from this customer's stored profile, prediction, risk factors and support history."
        actions={
          <Button size="sm" loading={generating} onClick={() => void generate()}>
            {!generating ? <Sparkles aria-hidden="true" className="h-3.5 w-3.5" /> : null}
            {latest ? "Regenerate recommendation" : "Generate recommendation"}
          </Button>
        }
      />

      {error ? (
        <ErrorState className="mt-5" message={error.message} code={error.code} onRetry={onReload} />
      ) : loading ? (
        <SkeletonText className="mt-5" lines={5} />
      ) : !latest ? (
        <div className="mt-5 rounded-2xl bg-sand-50 p-5">
          <p className="text-sm text-ink-700">
            No recommendation has been generated for this customer yet. Generating one calls Gemini through FastAPI and stores
            the result as a draft action; nothing is sent to the customer.
          </p>
        </div>
      ) : (
        <div className="mt-5 space-y-5">
          <div className="flex flex-wrap items-center gap-2">
            <Badge tone={latest.source === "gemini" ? "ai" : "neutral"}>
              {latest.source === "gemini" ? "AI generated (Gemini)" : `Rule-based fallback (${titleCase(latest.source)})`}
            </Badge>
            <Badge tone="info">{titleCase(latest.priority)} priority</Badge>
            <Badge tone="neutral">Status: {titleCase(latest.status)}</Badge>
            <span className="text-[11px] text-ink-700/65">Created {formatDate(latest.created_at)}</span>
          </div>

          <dl className="grid gap-5 sm:grid-cols-2">
            <KeyValue label="Strategy" value={latest.strategy ?? latest.title} />
            <KeyValue label="Recommended action" value={latest.recommended_action ?? latest.description ?? "—"} />
            <KeyValue
              label="Channel"
              value={latest.channel ? (CHANNEL_LABELS[latest.channel as MessageChannel] ?? titleCase(latest.channel)) : "—"}
            />
            <KeyValue label="Incentive" value={latest.incentive ? titleCase(latest.incentive) : "None suggested"} />
          </dl>

          <div>
            <p className="text-[11px] uppercase tracking-[0.14em] text-ink-700/60">Reasoning</p>
            <p className="mt-1.5 text-sm leading-6 text-ink-800">{latest.reasoning ?? latest.description ?? "—"}</p>
          </div>

          {records.length > 1 ? (
            <details className="rounded-2xl bg-sand-50 p-4">
              <summary className="cursor-pointer text-sm font-medium text-ink-900">
                Earlier recommendations ({records.length - 1})
              </summary>
              <ul className="mt-3 space-y-3">
                {records.slice(1).map((record) => (
                  <li key={record.id} className="rounded-2xl bg-white p-3 ring-1 ring-sand-200">
                    <p className="text-sm font-medium text-ink-900">{record.strategy ?? record.title}</p>
                    <p className="mt-1 text-xs leading-5 text-ink-700/75">{record.reasoning ?? record.description}</p>
                    <p className="mt-1 text-[11px] text-ink-700/60">
                      {titleCase(record.source)} · {formatDate(record.created_at)}
                    </p>
                  </li>
                ))}
              </ul>
            </details>
          ) : null}
        </div>
      )}

      <div className="mt-6 border-t border-sand-200 pt-5">
        <p className="text-sm font-semibold text-ink-900">Generate an outreach draft</p>
        <p className="mt-1 text-xs leading-5 text-ink-700/75">
          Drafts open in an editable review window. ChurnPilot never sends messages on your behalf.
        </p>
        <div className="mt-3 flex flex-wrap gap-2">
          {MESSAGE_CHANNELS.map((channel) => (
            <Button key={channel} variant="secondary" size="sm" onClick={() => onCompose(channel)}>
              Generate {CHANNEL_LABELS[channel]}
            </Button>
          ))}
        </div>
        <p className="mt-3 text-[11px] text-ink-700/60">Drafting for {customerName}.</p>
      </div>
    </Card>
  );
}
